export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  author: string;
  image: string;
  content: string;
  readingTime: string;
}

export const posts: BlogPost[] = [
  {
    slug: "deploy-react-coolify",
    title: "How to deploy React to Coolify using Docker",
    excerpt: "A step-by-step guide to writing the perfect multi-stage Dockerfile for React and Vite applications, optimized for Coolify deployments.",
    date: "May 8, 2026",
    category: "Engineering",
    author: "Alex Rivers",
    readingTime: "8 min read",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=1200",
    content: `
      <h2>Introduction</h2>
      <p>Self-hosting is becoming the preferred choice for many developers in 2026. Platforms like Coolify have made it incredibly easy to manage your own VPS as if it were a high-end PaaS. In this guide, we'll look at how to properly containerize a React + Vite application for production.</p>

      <h2>The Multi-Stage Dockerfile</h2>
      <p>The key to a small and secure production image is the multi-stage build. We don't need the entire Node.js runtime or our source code in the final production container. Instead, we build the application in an intermediate stage and then copy only the static assets to a lightweight server.</p>

      <pre><code># Build stage
FROM node:23-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]</code></pre>

      <h2>Why Coolify?</h2>
      <p>Coolify acts as an orchestrator. Once you point it to your repository, it reads your Dockerfile, builds the image, and handles the deployment. It also provides automatic SSL certificates via Traefik or Caddy, which simplifies your setup significantly.</p>

      <h2>Handling Client-Side Routing</h2>
      <p>One common issue with SPAs (Single Page Applications) like React is that reloading on a sub-page (e.g., /about) results in a 404 from the server. This is because the server doesn't know about your React routes. You must configure your server (NGINX or Express) to serve index.html for all non-file requests.</p>
    `
  },
  {
    slug: "nginx-config-spa",
    title: "The Ultimate NGINX Configuration for SPAs",
    excerpt: "Stop dealing with 404s on page refresh. Learn how to configure NGINX to properly serve React Router applications and cache static assets.",
    date: "April 24, 2026",
    category: "Architecture",
    author: "Sarah Chen",
    readingTime: "6 min read",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=1200",
    content: `
      <h2>The 404 Problem</h2>
      <p>If you've ever deployed a React app and noticed that refreshing the page on <code>/dashboard</code> leads to a generic "Not Found" page, you've encountered the classic SPA routing issue. Since the server looks for a physical <code>dashboard.html</code> file which doesn't exist, it fails.</p>

      <h2>The Solution</h2>
      <p>The configuration needs to tell NGINX to direct all traffic back to <code>index.html</code>, letting React Router handle the URL once the JavaScript loads.</p>

      <pre><code>server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}</code></pre>

      <h2>Caching for Performance</h2>
      <p>Static assets generated by Vite include hashes in their filenames (e.g., <code>index-B3f8k2.js</code>). This means they are immutable; they will never change. We can safely tell the browser to cache these files for a long time.</p>
    `
  },
  {
    slug: "self-hosting-vs-paas",
    title: "Why we chose self-hosting over PaaS in 2026",
    excerpt: "A deep dive into our decision-making process when moving our entire infrastructure from managed platforms to our own servers with Coolify.",
    date: "April 10, 2026",
    category: "Case Study",
    author: "James Wilson",
    readingTime: "12 min read",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200",
    content: `
      <h2>The Cost of Convenience</h2>
      <p>Managed platforms are great when you're starting out. They handle scaling, databases, and SSL with one click. But as your traffic grows, so does the bill. In late 2025, our monthly infrastructure costs hit $2,000, while the actual resource usage didn't justify the price tag.</p>

      <h2>The Freedom of Self-Hosting</h2>
      <p>By moving to Hetzner and DigitalOcean droplets managed by Coolify, we reduced our costs by 80% while increasing our hardware specs. We now have full control over our database backups, background workers, and monitoring tools.</p>

      <h2>Conclusion</h2>
      <p>The tools for self-hosting have matured. You no longer need a dedicated DevOps team to manage a few servers. For 90% of SaaS startups, self-hosting is now the most rational financial and technical choice.</p>
    `
  }
];
